apiVersion: v1
kind: Service
metadata:
  name: crawler-svc
  labels:
    app: sitemap-generator
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5002
  selector:
    app: sitemap-generator
